# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'GithubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubApp
  pod 'Alamofire', '~> 5.1'
  pod 'RealmSwift'

  target 'GithubAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubAppUITests' do
    # Pods for testing
  end

end
